---
# file: roles/cdh_hadoop_config/tasks/main.yml


- name: Copy Hadoop / HDFS configuration files
  template: src={{ item }} dest=/usr/local/hadoop/etc/hadoop/{{ item }} owner=root group=root mode=0644
  with_items:
    - core-site.xml
    - hadoop-env.sh
    - hadoop-metrics2.properties
    - hdfs-site.xml
    - slaves
    - dfs.hosts.exclude
  tags:
    - hadoop
    - configuration
    - restartHdfs
    - slaves
